### ISSUE TITLE
[Bug]: 自定义API使用PushDeer接口报错

### ISSUE THREAD

**Issue by iiwenwen** [catlair/BiliOutils#120]
### 运行环境和版本

阿里云函数

### 发生了什么

设置自定义API后日志报错，无法运行。

### 相关的日志输出

```shell
SyntaxError: Unexpected token 
 in JSON at position 132
    at parse (null:null:null)
    at customApi (/code/node_modules/@catlair/bilitools/dist/utils/sendNotify.js:149:27)
    at sendNotify (/code/node_modules/@catlair/bilitools/dist/utils/sendNotify.js:80:3)
    at sendMessage (/code/node_modules/@catlair/bilitools/dist/utils/sendNotify.js:631:3)
    at dailyTasks (/code/node_modules/@catlair/bilitools/dist/task/dailyTask.js:50:3)
    at run (/code/node_modules/@catlair/bilitools/dist/utils/serverless/index.js:58:12)
    at dailyMain (/code/node_modules/@catlair/bilitools/dist/index.fc.js:21:10)
    at handler (/code/node_modules/@catlair/bilitools/dist/index.fc.js:42:21)
```

### 相关的配置，注意个人隐私。

```json
自定义API配置：
api: {
        url:'https://api2.pushdeer.com/message/push',
        data:{
          pushkey:'{pushkey}',
          type: 'text',
          text:'{title}',
          desp:'{text}',
        },
```

### 有效的帮助

报错原因：{text}内容格式化为json后存在\n换行符号，导致JSON.pars()错误。

修复：在node_modules/@catlair/bilitools/dist/utils/sendNotify.js中148行，将str = JSON.stringify(data).replace(/{title}/g, title).修改为str = JSON.stringify(data).replace(/{title}/g, title).replace(/{text}/g, text).replace(/\n/g,'\\n');对字符串转义即可。

注意：PushDeer中默认格式为Markdown，会导致推送消息没有换行，需要指定类型为text。

**Comment by catlair** [comment]
阿哲，

**Comment by catlair** [comment]
感谢。
更新了，在你的基础上增加了r
```js
const str = JSON.stringify(data)
        .replace(/{title}/g, title)
        .replace(/{text}/g, text)
        .replace(/\n/g, '\\n')
        .replace(/\r/g, '\\r');
```

**Comment by catlair** [comment]
markdown 可能是需要两个 \n\n
