### ISSUE TITLE
[配置]: Error: Cannot find module 'D:\Tools\BiIli\package.json'

### ISSUE THREAD

**Issue by AQUOSZZY** [catlair/BiliOutils#139]
### 是否已经阅读文档

- [X] 我确定阅读过文档

### 运行环境和版本

本地Windows11，我是用更新命令更新的，应该是最新版本，我使用 `bilitools -v`的时候会报错：
`C:\Users\AQUOS>bilitools -v
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\AQUOS\package.json'
Require stack:
- C:\Users\AQUOS\AppData\Roaming\npm\node_modules\@catlair\bilitools\bin.js
[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)[39m
[90m    at Function.Module._load (node:internal/modules/cjs/loader:778:27)[39m
[90m    at Module.require (node:internal/modules/cjs/loader:1005:19)[39m
[90m    at require (node:internal/modules/cjs/helpers:102:18)[39m
    at Object.<anonymous> (C:\Users\AQUOS\AppData\Roaming\npm\node_modules\[4m@catlair[24m\bilitools\bin.js:14:13)
[90m    at Module._compile (node:internal/modules/cjs/loader:1101:14)[39m
[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)[39m
[90m    at Module.load (node:internal/modules/cjs/loader:981:32)[39m
[90m    at Function.Module._load (node:internal/modules/cjs/loader:822:12)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [
    [32m'C:\\Users\\AQUOS\\AppData\\Roaming\\npm\\node_modules\\@catlair\\bilitools\\bin.js'[39m
  ]
}`

### 发生了什么

本地运行报错，我的配置和日志文件是存放在'D:\Tools\BiIli'下的

### 相关的日志输出

```shell
2023/01/25 11:18:00 设置定时任务： 11:19:08
2023/01/25 11:19:13 cmd.Run() failed with exit status 1
2023/01/25 11:19:13 combined out:
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'D:\Tools\BiIli\package.json'
Require stack:
- C:\Users\AQUOS\AppData\Roaming\npm\node_modules\@catlair\bilitools\bin.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\AQUOS\AppData\Roaming\npm\node_modules\@catlair\bilitools\bin.js:14:13)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\AQUOS\\AppData\\Roaming\\npm\\node_modules\\@catlair\\bilitools\\bin.js'
  ]
}
```

**Comment by KudouRan** [comment]
感谢反馈，我想应该是最新的移动了目录结构，导致找 package.json 找错了位置，不影响正常使用。下次更新修复

**Comment by catlair** [comment]
已经修复了
