### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jjqqjjjj** [catlair/BiliOutils#202]
### 运行环境和版本

青龙面板 v2.15.17
BiliOutils v0.23.805

### 发生了什么

天选时刻与天选红包获取直播间列表异常,近期出现的问题

### 相关的日志输出

```shell
[❓ 00:29:07] 获取直播间列表异常： Timeout awaiting 'request' for 10000ms
[🐛 00:29:07] RequestError: Timeout awaiting 'request' for 10000ms
    at ClientRequest.<anonymous> (/root/.local/share/pnpm/global/5/.pnpm/got@11.8.6/node_modules/got/dist/source/core/index.js:970:65)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at origin.emit (/root/.local/share/pnpm/global/5/.pnpm/@szmarczak+http-timer@4.0.6/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Timeout.timeoutHandler [as _onTimeout] (/root/.local/share/pnpm/global/5/.pnpm/got@11.8.6/node_modules/got/dist/source/core/utils/timed-out.js:36:25)
    at listOnTimeout (node:internal/timers:571:11)
    at process.processTimers (node:internal/timers:512:7)
```

**Comment by KudouRan** [comment]
你是最近经常出现这个错误，且只在此处发生？这无解啊，timeout是网络的问题

**Comment by jjqqjjjj** [comment]
@catlair 刚去看了下又能正常使用了

**Comment by jjqqjjjj** [comment]
@KudouRan 刚去看了下又能正常使用了
